CREATE DATABASE QUANLYSINHVIEN3LOP_TEST
GO

USE QUANLYSINHVIEN3LOP_TEST
GO


CREATE TABLE MAJOR
(
	FALCULTYID INT ,
	MAJORID INT,
	NAME NVARCHAR(255)
	
	CONSTRAINT PK_MAJOR PRIMARY KEY (FALCULTYID,MAJORID)
	CONSTRAINT FK_MAJOR_FACULTY FOREIGN KEY (FALCULTYID) REFERENCES FACULTY(FACULTYID)
)
GO

DROP TABLE MAJOR

ALTER TABLE MAJOR
ADD CONSTRAINT FK_MAJOR_FACULTY FOREIGN KEY (FALCULTYID) REFERENCES FACULTY(FACULTYID)


CREATE TABLE STUDENT
(
	STUDENTID NVARCHAR (10) PRIMARY KEY ,
	FULLNAME NVARCHAR (255) ,
	AVERAGESCORE FLOAT ,
	FacultyId INT FOREIGN KEY REFERENCES FACULTY(FACULTYID)  ,
	MAJORID INT,
	AVATAR NVARCHAR(255)


	CONSTRAINT FK_STUDENT_FACULTY FOREIGN KEY (FacultyId) REFERENCES FACULTY(FACULTYID),
	CONSTRAINT FK_STUDENT_MAJOR FOREIGN KEY (FacultyId, MAJORID) REFERENCES MAJOR(FALCULTYID, MAJORID)
)


DROP TABLE STUDENT

--ALTER TABLE STUDENT
--ADD CONSTRAINT CHK_FULLNAME_NotNull CHECK (FULLNAME IS NOT NULL);

CREATE TABLE FACULTY 
(
	FACULTYID INT PRIMARY KEY,
	FACULTYNAME NVARCHAR (255)
)

ALTER TABLE FACULTY
ADD TotalProfessor INT NULL


ALTER TABLE STUDENT
ADD CONSTRAINT Fk_Student_Faculty FOREIGN KEY (FACULTYID) REFERENCES FACULTY(FACULTYID)
GO


ALTER TABLE STUDENT
ADD CONSTRAINT FK_STUDENT_MAJOR FOREIGN KEY (MAJORID) REFERENCES MAJOR(MAJORID)
GO


INSERT INTO FACULTY(FACULTYID,FACULTYNAME) VALUES  (1 , N'CÔNG NGHỆ THÔNG TIN'), (2,N'NGON NGU ANH'),(3,N'QUẢN TRỊ KINH DOANH') 
GO

INSERT INTO MAJOR (FALCULTYID , MAJORID , NAME) VALUES (1,1,N'CÔNG NGHỆ PHẦN MỀM')

INSERT INTO MAJOR (FALCULTYID , MAJORID , NAME) VALUES (2,1,N'TIẾNG ANH THƯƠNG MẠI ') , 
(1,2,N'HỆ THỐNG THÔNG TIN') , 
(2,2,N'TIẾNG ANH TRUYỀN THÔNG') , 
(1,3,N'AN TOÀN THÔNG TIN') 
GO


INSERT INTO STUDENT (STUDENTID,FULLNAME,AVERAGESCORE,FacultyId,MAJORID,AVATAR) VALUES 
(1234567890 , N'NGUYỄN VĂN B' , 7.5 , 1 ,1,N'1234567890.jpg' ),

INSERT INTO STUDENT (STUDENTID,FULLNAME,AVERAGESCORE,FacultyId,MAJORID,AVATAR) VALUES 
(1234567891 , N'NGUYỄN VĂN A' , 4.5 , 1 ,2,N'1234567891.jpg' ),

INSERT INTO STUDENT (STUDENTID,FULLNAME,AVERAGESCORE,FacultyId,MAJORID,AVATAR) VALUES
(1234567892 , N'NGUYỄN VĂN C' , 10 , 2 ,NULL,N'1234567892.jpg' )











